---
title: "Untitled"
output: html_document
---

```{r}
library(rvest) # web scraping
library(dplyr)
library(stringr)
library(igraph)
```




Urls that contain boxer's record
```{r}
urls = c('https://en.wikipedia.org/wiki/Anthony_Joshua',
         'https://en.wikipedia.org/wiki/Deontay_Wilder',
         'https://en.wikipedia.org/wiki/Tyson_Fury',
         'https://en.wikipedia.org/wiki/Dillian_Whyte', # make sure u get right record
         'https://en.wikipedia.org/wiki/Alexander_Povetkin')
```

Extract boxer's name from urls
```{r}
boxer_names <- str_replace_all(urls, '.+wiki\\/', '') %>% 
  str_replace_all('_', ' ') %>% str_replace_all(' \\(.+', '')
```

Extract boxer's win/loss record
```{r}
# col names that ids a win/loss record
req_names = c("Result", "Record", "Opponent")
record_lst = list()

# for each boxer extract win/loss record
for (i in 1:length(urls)){
  # read tables on webpage
  tbl <- read_html(urls[i]) %>% 
    html_nodes(css = 'table')
  # print(paste0("i: ",  i))
  
  # for each table check if it's the win/loss record
  for (j in 1:length(tbl)){
    # convert html table to dataframe
    record_temp = tbl[j] %>% html_table(fill = TRUE) %>% as.data.frame()
    # check if the names in table look like a table with win/loss record 
    if(length(intersect(req_names, record_temp %>% names())) == 3) {
      # save the index of table with win/loss record
      record_i = j
    }
  }
  # convert win/loss record html table to dataframe
  record = tbl[record_i] %>% html_table() %>% as.data.frame()
  
  record_lst[[i]] = record
}
```

Filter record for wins only
```{r}
win_record = list()
for(i in 1:length(record_lst)){
  win_record[[i]] <- record_lst[[i]] %>% 
    filter(Result == "Win") %>% mutate(boxer = boxer_names[i])
}


```

```{r}
relations <- bind_rows(win_record)

relations <- relations %>% mutate(from = boxer, to = Opponent) %>%
  select(from, to, Type)

boxers = data.frame(name = union(boxer_names, relations$to))

g <- graph_from_data_frame(relations, directed = T, vertices = boxers)

plot(g)
```

```{r}
foo <- adjacent_vertices(g, "Deontay Wilder", mode = "out")

foo$`Anthony Joshua`
```


```{r}
actors <- data.frame(name=c("Alice", "Bob", "Cecil", "David",
                            "Esmeralda"),
                     age=c(48,33,45,34,21),
                     gender=c("F","M","F","M","F"))

relations <- data.frame(from=c("Bob", "Cecil", "Cecil", "David",
                               "David", "Esmeralda"),
                        to=c("Alice", "Bob", "Alice", "Alice", "Bob", "Alice"),
                        same.dept=c(FALSE,FALSE,TRUE,FALSE,FALSE,TRUE),
                        friendship=c(4,5,5,2,1,1), advice=c(4,5,5,4,2,3))

g <- graph_from_data_frame(relations, directed=TRUE, vertices=actors)
print(g, e=TRUE, v=TRUE)
```

